version: '3'
services:
  exporter:
    image: sge_exporter
    environment:
      SGE_CELL: "YOUR_SGE_CELL"
      PORT: "YOUR_PORT"
    volumes:
      - /var/lib/gridengine:/var/lib/gridengine:ro
      - /usr/lib/gridengine:/usr/lib/gridengine:ro
    network_mode: "host"
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./prometheus/prom.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    environment: 
      GF_SECURITY_ADMIN_PASSWORD: "admin"
