global:
  scrape_interval: 45s
  evaluation_interval: 30s

scrape_configs:
  - job_name: exporter
    scrape_interval: 30s
    metrics_path: /metrics
    honor_labels: true
    static_configs:
      - targets: ["exporter:9081"]