# .goreleaser.yml
nfpms:
  # note that this is an array of nfpm configs
  -
    # ID of the nfpm config, must be unique.
    # Defaults to "default".
    id: gridengine_prometheus
    # You can change the name of the package.
    # Default: `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

    # Your app's vendor.
    # Default is empty.
    vendor: Metrum Research Group
    # Your app's homepage.
    # Default is empty.
    homepage: https://metrumrg.com/

    # Your app's maintainer (probably you).
    # Default is empty.
    maintainer: Darrell Breeden <darrellb@metrumrg.com>

    # Your app's description.
    # Default is empty.
    description: Prometheus Exporter for the Sun Grid Engine

    # Your app's license.
    # Default is empty.
    license: MIT

    # Formats to be generated.
    formats:
      - deb
      - rpm

    # Packages your package depends on.
    dependencies:
      - bash

    # Packages your package recommends installing.
    # For RPM packages rpmbuild >= 4.13 is required
    recommends:
      - git

    # Override default /usr/local/bin destination for binaries
    bindir: /usr/local/bin/

    # Empty folders that should be created and managed by the packager
    # implementation.
    # Default is empty.

    contents:
      - dst: /var/log/gridengine_prometheus
        type: dir
      - dst: /etc/gridengine_prometheus
        type: dir
      - src: "scripts/gridengine_prometheus.service"
        dst: "/etc/systemd/system/gridengine_prometheus.service"
      - src:  "scripts/gridengine_prometheus.sh"
        dst: "/etc/init.d/gridengine_prometheus"
      - src: "scripts/gridengine_prometheus.yaml"
        dst: "/etc/gridengine_prometheus/config.yaml"

    # Scripts to execute during the installation of the package.
    # Keys are the possible targets during the installation process
    # Values are the paths to the scripts which will be executed
    scripts:
      postinstall: "scripts/postinstall.sh"
builds:
  -
    id: "default"
    ldflags:
      - -s -w -X 'github.com/metrumresearchgroup/gridengine_prometheus/cmd.Version={{ .Env.VERSION }}'

archives:
  -
    builds:
      - default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz